kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo ${DRONE_REPO_BRANCH}
  - echo $DRONE_REPO_BRANCH
  - echo $${DRONE_REPO_BRANCH}
  - ls -al
  - pwd
  - whoami
