kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo ${DRONE_COMMIT_SHA}
  - echo $DRONE_COMMIT_SHA
  - echo $${DRONE_COMMIT_SHA}
  - ls -al
  - pwd
  - whoami
trigger:
  branch:
    include:
    - master
  event:
  - pull
